name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: 'Breaking'
    label: 'breaking'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
autolabeler:
  - label: 'breaking'
    title:
      - '/breaking/i'
  - label: 'enhancement'
    title:
      - '/feat/i'
exclude-labels:
  - 'skip-changelog'
exclude-contributors:
  - 'fcying'

