name: Release

on:
  push:
    branches: [ master, test ]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      # - name: Run Release Drafter
      #   id: release_drafter
      #   uses: release-drafter/release-drafter@v5
      #   with:
      #     config-name: release-drafter.yml
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update latest
        uses: ncipollo/release-action@v1
        with:
          tag: test
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          name: test version ${{ env.COMMIT }}
          draft: true
